### DISCUSSION TITLE
Not sure how to install on Linux Minf.  PPA not working and not sure how to generate config.xml in Docker

### DISCUSSION THREAD

**Discussion by TheeDudenator** [gerbera/gerbera#2991] [General]
PPA/repository not working - I am Linux Mint 21.3 (Jammy)
I am new to Docket, but I got the container installed and I can get to the Webgui for 2.0 Gerbera.

I can map the config.xml.   But I have no idea how to create the intial config.xml within docker.

**Comment by KarlStraussberger** [comment]
It's quite simple: You need to map the volume for the config to some directory on your host.  Then it is autogenerated on first start and you can update it.

https://github.com/gerbera/gerbera/blob/master/README.Docker.md

**Reply by seiha011** [reply]
Hi, unfortunately this does not work
```
volumes:
      - gerbera-config:/var/run/gerbera
      - /some/files:/mnt/content:ro
volumes:
  gerbera-config:
    external: false
```
If I enter "- gerbera-config:/path_at_host"
I can access this path form the web-gui, but there is no config.xml autogenerated.
Are there any gerbera-logfles, which can be accessed from outside the docker-container (or from the weg-GUI)?
The "path_at_host" has the same UID and GUI as the docker-container...

**Reply by seiha011** [reply]
```
### https://hub.docker.com/r/gerbera/gerbera
### Port 49494/tcp (HTTP) and 1900/udp (SSDP Multicast) are exposed by default.      
---
services:
  gerbera:
    image: gerbera/gerbera
    privileged: true
    container_name: gerbera
    network_mode: host
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=${TIME_ZONE_VALUE}    # from global.env
    volumes:
      # - gerbera-config:/var/run/gerbera
      - gerbera-config:${PATH_TO_APPDATA}/gerbera
      - /srv/dev-disk-by-uuid-ffe85eb1-39b1-439e-b846-3e2b55a22e93/music/:/mnt/music:ro
      - /srv/dev-disk-by-uuid-ffe85eb1-39b1-439e-b846-3e2b55a22e93/video/:/mnt/video:ro
      - /srv/dev-disk-by-uuid-ffe85eb1-39b1-439e-b846-3e2b55a22e93/photo/:/mnt/photo:ro
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/dri:/dev/dri
  volumes:
  gerbera-config:
    external: false
    
```
