### DISCUSSION TITLE
Access behind reverse proxy... caddy?

### DISCUSSION THREAD

**Discussion by indigomirage** [gerbera/gerbera#3303] [Q&A]
Hi there -

Wasn't sure where else to post, but I'm not having any luck with gerbera (running on docker) behind a caddy reverse proxy.

I've got several other websites working well under this configuration as follows in my Caddyfile:

gerbera.myhost.xyz:443 {
        reverse_proxy http://localhost:49494
        tls /usr/share/caddy/cert/gerbera.myhost.xyz-cert.fullchain /usr/share/caddy/cert/gerbera.myhost.xyz-cert-acmecert.key
}

But I cannot seem to get the gerbera page to load under https://gerbera.myhost.xyz (":443", whether explicit or implied).

I've tried every combo I can think of in the gerbera config (via http://gerbera.myhost.xyz:49494) for both Virtual Url and External Url, but it's just not loading.

If it's a caddy-specific issue, so be it, but the same pattern works very well on several other sites.  Is there something obvious missing here?

I'm running Gerbera  2.3.0 on docker with host networking (jellyfin works this way, also with host networking), and the gerbera container is running, and indexing my media.

I'm at a loss here - any ideas or places to look would be very helpful.

(Thank you, BTW, for resurrecting mediatomb - it was the best, and virtual folders are a killer feature that I've seen nowhere else!)

**Comment by nobanzai** [comment]
> cannot seem to get the gerbera page to load

means what? What does your browser say?
I don't know anything about caddy, but is it a terminating proxy?

**Comment by cmigliorini** [comment]
I was able to get this to work with an NGinx and Gerbera 3.1.0.

The trick is that because of uPnP, you need to use `network_mode: host` to [get Gerbera to send/receive multicast](https://gist.github.com/ddimtirov/5b61a697218e3e49a9b2b6e1b7e73ef2), so you need to pick a different port (or perhaps get into something more complex with your reverse proxy _not_ in `network_mode: host`).

TBH, the reason why I needed that is weird : despite the host mode, my web page -- worse, the actual media server -- is not accessible from outside the host. Perhaps I'll find how to overcome this.

Anyway, here's what I put together
## `./nginx/nginx.conf`
```conf
events {}
http {
  server {
    listen 8200;

    location / {
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host   $host:$server_port;
        proxy_set_header   X-Forwarded-Server $host;

          proxy_pass         http://IPV4:49200/; # Did not try IPV6, but it should work too
    }
  }
}
```
## `compose.yaml`
```yaml
services:
  gerbera:
    image: gerbera
    container_name: gerbera-gerbera
    network_mode: host
    user: gerbera
    volumes:
      - ./gerbera-config:/var/run/gerbera
      - /data/multimedia:/mnt/content:ro
    command: gerbera --port 49200 --config /var/run/gerbera/config.xml

  nginx:
    image: nginx
    container_name: gerbera-nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
```
