### ISSUE TITLE
weird behaviour on ARM in Docker

### ISSUE THREAD

**Issue by hmoffatt** [gerbera/gerbera#2485]
I have Gerbera running as I like it on an x86-64 system in Docker, and now I'm trying to run the same on an ARM system.

When I start it the first time it exits with error 139. The timestamps in the log are very weird too

```
$ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating gerbera ... done
Attaching to gerbera
gerbera    | 1970-01-01 00:03:22   info: Gerbera UPnP Server v1.10.0-15-g7bb7422d - http://gerbera.io/
gerbera    | 1972-03-19 05:36:36   info: Copyright 2016-2022 Gerbera Contributors.
gerbera    | 1972-03-19 05:36:36   info: Gerbera is free software, covered by the GNU General Public License version 2
gerbera    | 1970-01-01 00:00:10   info: Loading configuration from: /var/run/gerbera/config.xml
gerbera    | 1969-12-31 23:59:59   info: Checking configuration...
gerbera    | 1866-10-15 05:58:39   info: Configuration check succeeded.
gerbera    | 2202-02-11 15:26:29 warning: Sqlite3 database seems to be corrupt or doesn't exist yet.
gerbera    | 2202-02-11 15:26:29   info: No sqlite3 backup is available or backup is corrupt. Automatically creating new database file...
gerbera    | 1713-05-02 16:26:09   info: database created successfully.
gerbera    | 1970-01-01 00:00:00   info: Loading 0 configuration items from database
gerbera exited with code 139
```

Next time I start it it goes further but prints libupnp errors.

```
$ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting gerbera ... done
Attaching to gerbera
gerbera    | 1970-01-01 00:03:22   info: Gerbera UPnP Server v1.10.0-15-g7bb7422d - http://gerbera.io/
gerbera    | 1972-03-19 05:36:36   info: Copyright 2016-2022 Gerbera Contributors.
gerbera    | 1972-03-19 05:36:36   info: Gerbera is free software, covered by the GNU General Public License version 2
gerbera    | 1970-01-01 00:00:10   info: Loading configuration from: /var/run/gerbera/config.xml
gerbera    | 1969-12-31 23:59:59   info: Checking configuration...
gerbera    | 1747-05-20 11:36:06   info: Configuration check succeeded.
gerbera    | 1970-01-01 00:00:00   info: Loading 0 configuration items from database
gerbera    | 1970-01-01 00:57:30   info: Loading autoscan location: /content; recursive: true, last_modified: unset
gerbera    | 1970-01-01 00:03:39   info: Initialising UPnP with interface: <unset>, port: 49494
gerbera    | 1970-01-01 00:00:43   info: IPv4: Server bound to: 192.168.42.162:49494
gerbera    | 1970-01-01 00:00:42   info: IPv6: Server bound to: fe80::21e:6ff:fe36:dc1b:49494
gerbera    | 1970-01-01 00:00:42   info: IPv6 ULA/GLA: Server bound to: 2403:5801:1c:42:21e:6ff:fe36:dc1b:49494
gerbera    | 1970-01-01 00:00:00   info: Will send UPnP Alive advertisements every 870 seconds
gerbera    | 1970-01-01 00:00:11   info: The Web UI can be reached by following this link: http://192.168.42.162:49494
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
gerbera    | libupnp ThreadPoolAdd too many jobs: 100
```

It prints a lot of those libupnp errors.

When I connect to http://192.168.42.162:49494 it just prints 'internal server error'. It doesn't appear on the network as a UPnP device either.

My docker-compose file is simply

```
---
version: "2.3"

services:
  gerbera:
    image: gerbera/gerbera:sha-7bb7422-transcoding
    container_name: gerbera
    network_mode: host
    user: 1000:100
    volumes:
      - ./data:/var/run/gerbera
      - ./config.xml:/var/run/gerbera/config.xml:ro
      - ./import.js:/var/run/gerbera/import.js:ro
      - ../Music:/content:ro
```

The import scan has run OK as I see content items in the database.

**Comment by hmoffatt** [comment]
My docker-compose file is simply

```
---
version: "2.3"

services:
  gerbera:
    image: gerbera/gerbera:sha-7bb7422-transcoding
    container_name: gerbera
    network_mode: host
    user: 1000:100
    volumes:
      - ./data:/var/run/gerbera
      - ./config.xml:/var/run/gerbera/config.xml:ro
      - ./import.js:/var/run/gerbera/import.js:ro
      - ../Music:/content:ro
```
