### ISSUE TITLE
Gerbera Ubuntu repo

### ISSUE THREAD

**Issue by tommyp-vr4** [gerbera/gerbera#2603]
Hi - The new LTS Ubuntu came out a few days back.  I've working in some VMs to be sure my setups are correct.  I didn't have success installing Gerbera on it.    
1 - The Ubuntu installation instructions are a bit off.   The curl command appears to be outdated.   Here's the error I get.  
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`
2 - Can the setup instructions be reworded to use wget instead of curl?  (A bare bones ubuntu doesn't have curl installed but is no big deal to install.) 
3 - The https://gerbera.jfrog.io and https://gerbera.jfrog.io/artifactory/debian come up in a browser but the sites get rerouted to https://gerbera.jfrog.io/ui/login/ and prompts me for a username and password.  I could have sworn that 2nd site showed the repos at one point in time.  
4 - My real box that I want to update is currently running Ubuntu Bionic (18.04.6 LTS).  I can't get it to updated from Gerbera v1.9.2 to the latest either.

**Comment by neheb** [comment]
```
sudo apt install meson
git clone https://github.com/gerbera/gerbera
curl https://patch-diff.githubusercontent.com/raw/gerbera/gerbera/pull/1868.patch | git apply
meson build
cd build
ninja
sudo ninja install
```

Something like that should work.

**Comment by whyman** [comment]
Hi @tommyp-vr4, thanks for the reminder.

I will put together a PR to build the deb packages for 22.04.

For 1 and 2 a PR for the docs would be appreciated!

> 3 - The https://gerbera.jfrog.io/ and https://gerbera.jfrog.io/artifactory/debian come up in a browser but the sites get rerouted to https://gerbera.jfrog.io/ui/login/ and prompts me for a username and password. I could have sworn that 2nd site showed the repos at one point in time.

Yeah, this is new and annoying, I will see if there is an option to to turn it off, browsing would make it easier.

> 4 - My real box that I want to update is currently running Ubuntu Bionic (18.04.6 LTS). I can't get it to updated from Gerbera v1.9.2 to the latest either.

This should work, what problem are you having? Is that machine set to use the https://gerbera.jfrog.io/  repo?

**Comment by whyman** [comment]
As a follow up 18.04 on ARM is excluded currently, because new enough cmake is not available in the CMake PPA:

```yaml
        exclude:
          - os-ver: "ubuntu:18.04" # No Cmake backport for these versions
            arch: linux/arm/v7
          - os-ver: "ubuntu:18.04"
            arch: linux/arm64/v8
          - os-ver: "ubuntu:20.04" # CMake PPA broken: https://gitlab.kitware.com/cmake/cmake/-/issues/22683
            arch: linux/arm/v7
```
