### ISSUE TITLE
Debug mode fails when using docker image

### ISSUE THREAD

**Issue by ItsMeMarc** [gerbera/gerbera#2660]
Hi,

On my Raspberry Pi 4 (4GB, Bullseye, 64 bit) I use Gerbera as Docker image.
Since I have problems with some video files, I want to switch to debug mode for further investigation. 
At first I tried it with docker compose:
```
version: "2.1"
services:
  gerbera:
    image: gerbera/gerbera:1.11.0-transcoding
    container_name: gerbera
    command: --debug --logfile /var/run/gerbera/gerbera.log
    network_mode: host
    volumes:
      - ./config:/var/run/gerbera:rw
      - /media/pi/raid/Videos/TEMP:/content_video:ro
```

But I get the following error message:
```
pi@RPi4:~/docker-compose-data/gerbera $ docker-compose up
Starting gerbera ... done
Attaching to gerbera
gerbera    | /usr/local/bin/docker-entrypoint.sh: exec: line 26: illegal option --
gerbera exited with code 2
```
After that I tried it via CLI:
```
docker run \
    --name gerbera-debug \
    --network=host \
    -v /home/pi/docker-compose-data/gerbera/config:/var/run/gerbera:rw \
    -v /media/pi/raid/Videos/TEMP:/content_video:ro  \
    gerbera/gerbera:1.11.0-transcoding --debug --logfile /var/run/gerbera/gerbera.log
```

But with that I get the same error message:
```
/usr/local/bin/docker-entrypoint.sh: exec: line 26: illegal option --
```

What do I have to do to switch to debug mode using Docker?

Regards
Marc
