### ISSUE TITLE
Errors  Invalid Session ID  - Cannot see file system

### ISSUE THREAD

**Issue by TheeDudenator** [gerbera/gerbera#2965]
When I try to add a folder, it says it does.
Then when I try to open the folder and look, I get Invalid Session ID.

I had this working fine, not sure what happened.
Maybe a permissions issue>

Linux Mint 21.2
I should have the latest Gerbera installed.

Any suggestions if there is a forum to help with issues?  Or is this it?

**Comment by KarlStraussberger** [comment]
Problems with session id should have gone since some years.
What do you get when calling `gerbera --compile-info`.

Also, it might help to clear the browser cache and cookies - at least for the gerbera page.

**Comment by TheeDudenator** [comment]
I am using Firefox
I cleared cache and history and restarted browser.
Same issue.
Depending on what I do, I also get "The System Encountered and Error"

This could be a permissions issue??

**Comment by TheeDudenator** [comment]
gerbera --compile-info

Gerbera UPnP Server v2.0.0-16-g49fa8ccd
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=OFF
WITH_MAGIC=ON
WITH_MYSQL=ON
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=ON
WITH_AVCODEC=ON
WITH_FFMPEGTHUMBNAILER=ON
WITH_EXIF=ON
WITH_EXIV2=ON
WITH_MATROSKA=ON
WITH_WAVPACK=ON
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF

Git info:
-------------
Git Branch: refs/heads/master
Git Commit: 49fa8ccda35d6f32e101466994668b4549b7f55b

**Comment by KarlStraussberger** [comment]
From which version did you upgrade? Did the new version install into the same directory as the old.

You should check the contents of `/usr/local/share/gerbera` (or `/usr/share/gerbera`) for old files. It's the directory your config points to.

**Comment by KarlStraussberger** [comment]
It's either /usr/local/share/gerbera or /usr/share/gerbera.

It should contain to following files
```
js/...
mysql.sql
mysql-upgrade.xml
sqlite3.sql
sqlite3-upgrade.xml
web/...
```

If you uninstall, you should make sure that everything is gone (if there were remnant from previous installations)

`.config/gerbera` is not part of the installation and does not have to be removed. After installation you can run `gerbera --create-config` and compare it with your `config.xml`.

**Comment by ynurmahomed** [comment]
Hi I'm getting this error on a fresh install using docker
```
version: "2.1"
services:
  gerbera:
    image: gerbera/gerbera
    container_name: gerbera
    network_mode: host
    volumes:
      - gerbera-config:/var/run/gerbera
      - /mnt/fb02fa1e-5ae3-4c71-b70f-d710eaf1ae5d/Movies/:/mnt/content:ro
    restart: unless-stopped

volumes:
  gerbera-config:
    external: false
```
